#!/usr/bin/python3

import unittest
from test_HTMLSegmentFormatter      import TestAdd_HTMLSegmentFormatter

def toonsite_suite():
    suite   = unittest.TestSuite()
    result  = unittest.TestResult()
    suite.addTest(unittest.makeSuite(TestAdd_HTMLSegmentFormatter))
    runner  = unittest.TextTestRunner(verbosity=2)
    print(runner.run(suite))

print("\n\n\tunit testing toonsite\n")
toonsite_suite()
print()
