#!/usr/bin/python3

import unittest
from test_MODULE    import TestAdd_MODULE

def PROJECT_suite():
    suite   = unittest.TestSuite()
    result  = unittest.TestResult()
    suite.addTest(unittest.makeSuite(TestAdd_MODULE))
    runner  = unittest.TextTestRunner(verbosity=2)
    print(runner.run(suite))

print("\n\n\tunit testing PROJECT\n")
PROJECT_suite()
print()
